from sc2.constants import *
BUILDING_DEPENDENCIES = {
  HATCHERY: [],
  EXTRACTOR: [],
  SPAWNINGPOOL: [HATCHERY],
  EVOLUTIONCHAMBER: [HATCHERY],
  LAIR: [SPAWNINGPOOL],
  ROACHWARREN: [SPAWNINGPOOL],
  BANELINGNEST: [SPAWNINGPOOL],
  LAIR: [SPAWNINGPOOL],
  HYDRALISKDEN: [LAIR],
  INFESTATIONPIT: [LAIR],
  HIVE: [INFESTATIONPIT],
  ULTRALISKCAVERN: [HIVE],
  GREATERSPIRE: [HIVE],
}

UNIT_DEPENDENCIES = {
  ZERGLING: [SPAWNINGPOOL],
  QUEEN: [SPAWNINGPOOL],
  ROACH: [ROACHWARREN],
  RAVAGER: [ROACHWARREN],
  BANELING: [BANELINGNEST],
  SWARMHOSTMP: [INFESTATIONPIT],
  INFESTOR: [INFESTATIONPIT],
  ULTRALISK: [ULTRALISKCAVERN],
  BROODLORD: [GREATERSPIRE]
}

RESEARCH_DEPENDENCIES = {
  ZERGMELEEWEAPONSLEVEL1: [EVOLUTIONCHAMBER],
  ZERGMELEEWEAPONSLEVEL2: [LAIR, ZERGMELEEWEAPONSLEVEL1],
  ZERGMELEEWEAPONSLEVEL3: [HIVE, ZERGMELEEWEAPONSLEVEL2],
  ZERGGROUNDARMORSLEVEL1: [EVOLUTIONCHAMBER],
  ZERGGROUNDARMORSLEVEL2: [LAIR, ZERGGROUNDARMORSLEVEL1],
  ZERGGROUNDARMORSLEVEL3: [HIVE, ZERGGROUNDARMORSLEVEL2],
  ZERGMISSILEWEAPONSLEVEL1: [EVOLUTIONCHAMBER],
  ZERGMISSILEWEAPONSLEVEL2: [LAIR, ZERGMISSILEWEAPONSLEVEL1],
  ZERGMISSILEWEAPONSLEVEL3: [HIVE, ZERGMISSILEWEAPONSLEVEL2],
}

IN_PROGRESS = "IN_PROGRESS"
